### ISSUE TITLE
Plugin Approval

### ISSUE THREAD

**Issue by NyakudyaA** [afonsoeam/geopec#1]
# Problem

Please fix the issue tracker link it currently goes to the repo. And also please provide a small description of what the plugin does

**Comment by afonsoeam** [comment]
> 
> # Problem
> 
> Please fix the issue tracker link it currently goes to the repo. And also please provide a small description of what the plugin does

All considerations have been fixed. It's necessary upload again in QGIS plugin site?

**Comment by NyakudyaA** [comment]
> > # Problem
> > Please fix the issue tracker link it currently goes to the repo. And also please provide a small description of what the plugin does
> 
> All considerations have been fixed. It's necessary upload again in QGIS plugin site?

Approved. thanks
